sudo: required
services:
  - docker

before_install:
  - docker build -t znoori455/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true znoori455/react-test npm test

after_success:
  - docker build -t znoori455/multi-client ./client
  - docker build -t znoori455/multi-nginx ./nginx
  - docker build -t znoori455/multi-server ./server
  - docker build -t znoori455/multi-worker ./worker
  # login to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take the imagees created and push them to docker hub
  - docker push znoori455/multi-client
  - docker push znoori455/multi-nginx
  - docker push znoori455/multi-server
  - docker push znoori455/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker2-env
  bucket_name: elasticbeanstalk-us-east-2-403594414960
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
